### ISSUE TITLE
Linux to Windows convert no animation in `.ani` file

### ISSUE THREAD

**Issue by mangkoran** [quantum5/win2xcur#10]
Animated cursor such as wait is not animating after converting from Xcursor to Windows cursor.

Step to produce:
1. Extract zip
2. Convert cursor using `x2wincur`
3. Install cursor file manually in Windows 
![image](https://user-images.githubusercontent.com/57625126/160323927-a40b60ce-8b8c-4573-8f46-52360fe8b339.png)

[Simp1e-Gruvbox-Dark.zip](https://github.com/quantum5/win2xcur/files/8359518/Simp1e-Gruvbox-Dark.zip)

Alternative download: https://store.kde.org/p/1405210

Update: Tested using `DMZ-White` just now, `.ani` files are not animated either.

**Comment by quantum5** [comment]
The `.ani` files are animated, just 1000 times too slow due to a bug in the Xcursor parser. This is fixed in fcf96813719736e25f457c94599b017d52469f16.

**Comment by mangkoran** [comment]
Thank you for the quick fix. I already tested and it is animated properly now. However, is there any way to speed up the animation? I tried changing the variable to `10000` (speed up 10x) but it seems failed.

**Comment by quantum5** [comment]
The `.ani` format measures time between frames with "jiffies", which are defined as 1/60th of a second. It is therefore impossible to animate faster than 60 fps.

**Comment by mangkoran** [comment]
Alright then. The issue could be closed then!
