### ISSUE TITLE
nix flake support

### ISSUE THREAD

**Issue by danmur97** [quantum5/win2xcur#18]
Hi, I am using NixOS and want to use `win2xcur`. The installation step with `pip` is not a very nix-way of installing things, so a nix flake build support will be wonderful.

**Comment by Atemu** [comment]
Note that win2xcur is packaged in Nixpkgs.

**Comment by danmur97** [comment]
Yes, but not as a flake. The PR also includes a development environment via nix so that dev setup is very straight forward.

**Comment by Atemu** [comment]
`nix develop nixpkgs#win2xcur`

**Comment by danmur97** [comment]
I will create a new issue regarding the development environment
