### ISSUE TITLE
Cannot convert .ani file

### ISSUE THREAD

**Issue by martymac** [quantum5/win2xcur#5]
Hello,

Thanks for providing win2xcur!

I've got problems trying to convert an .ani file (gzipped / attached) :

[pen.ani.gz](https://github.com/quantum5/win2xcur/files/5966400/pen.ani.gz)

$ win2xcur pen.ani
Error occurred while processing pen.ani:
Traceback (most recent call last):
  File "/home/martymac/.local/lib/python3.7/site-packages/win2xcur/main/win2xcur.py", line 46, in process
    cursor = open_blob(blob)
  File "/home/martymac/.local/lib/python3.7/site-packages/win2xcur/parser/__init__.py", line 17, in open_blob
    raise ValueError('Unsupported file format')
ValueError: Unsupported file format

Any hint ?

**Comment by quantum5** [comment]
This cursor is actually invalid. Looking at the hexdump, you see that the first two lines are:

```
00000000: 5249 4646 0a09 0000 4143 4f4e 616e 6968  RIFF....ACONanih
00000010: 2400 0000 2400 0000 0100 0000 0100 0000  $...$...........
```

The size field is `0a09 0000` or `0x90a`, which is 2314 bytes. This size is supposed to indicate the number of bytes that comes after the first 8, so the total file size needs to be 8 bytes longer. However, the entire file is only 2314 bytes long:

```
$ wc -c pen.ani 
2314 pen.ani
```

You can fix the ani file by changing `0a09 0000` to `0209 0000` and the cursor should convert.

**Comment by martymac** [comment]
Great, I'll try that, thanks a lot!

**Comment by MaitreGEEK** [comment]
Hello, I have the same issue with this file 

Error occurred while processing Téléchargements/chroma-curseur-black-petit/chroma_link_select.ani:
Traceback (most recent call last):
  File "/home/maitregeek/.local/lib/python3.10/site-packages/win2xcur/main/win2xcur.py", line 43, in process
    cursor = open_blob(blob)
  File "/home/maitregeek/.local/lib/python3.10/site-packages/win2xcur/parser/__init__.py", line 17, in open_blob
    raise ValueError('Unsupported file format')
ValueError: Unsupported file format
[chroma_link_select.ani.tar.gz](https://github.com/user-attachments/files/15521856/chroma_link_select.ani.tar.gz)
