### ISSUE TITLE
miku.ani File Format is Unsupported 

### ISSUE THREAD

**Issue by ghost** [quantum5/win2xcur#6]
Whenever I try converting this specific .ani file, I end up getting an error.
```
$ win2xcur input/miku.ani -o output/
Error occurred while processing input/miku.ani:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/win2xcur/main/win2xcur.py", line 46, in process
    cursor = open_blob(blob)
  File "/home/user/.local/lib/python3.9/site-packages/win2xcur/parser/__init__.py", line 17, in open_blob
    raise ValueError('Unsupported file format')
ValueError: Unsupported file format
```

The provided link is the Miku chan cursor set, created by RyanKun and released to the Public Domain.
The .ani file used for this error is `Miku Cursor 2.ani`
http://www.rw-designer.com/cursor-set/miku-chan
[Miku Cursor 2.ani](http://www.rw-designer.com/cursor-download.php?id=67201)

**Comment by quantum5** [comment]
This is the same problem as #5: the file is broken. You can fix it by changing fifth byte of the file to 0x6C. Given how common such broken files are, maybe I should relax the check...
