### ISSUE TITLE
x2wincur not respecting transparency

### ISSUE THREAD

**Issue by EwanGreen4** [quantum5/win2xcur#7]
X Cursor before conversion: 
![image](https://user-images.githubusercontent.com/36348486/121206653-e40fe180-c835-11eb-8811-4d74aa185328.png)
Windows Cursor after conversion: 
![image](https://user-images.githubusercontent.com/36348486/121208459-4e755180-c837-11eb-8de4-e82b2220adc6.png)
Files (Includes extension-less X cursor and .ico):
[arrow.zip](https://github.com/quantum5/win2xcur/files/6617569/arrow.zip)

No idea what could have caused this. Maybe some sort of overcompensation of color-to-alpha for cursors with black as the background for legacy support or something? I have no idea about the history of .ico or how this program looks under the hood. Just speculation.

**Comment by quantum5** [comment]
Your zip files does not include the X cursor.

**Comment by EwanGreen4** [comment]
Oops.

[arrow.zip](https://github.com/quantum5/win2xcur/files/6619261/arrow.zip)

This one should have both.

**Comment by DirtPiper** [comment]
I'm having the exact same issue.
Below is a zip file containing both xcursors and the converted wincursors.

For these cursors, the areas in _red_ are the ones being turned into transparency, so I don't think it's specifically black. Perhaps  the error is with ImageMagick?
[x2wincur_error.zip](https://github.com/quantum5/win2xcur/files/6619248/x2wincur_error.zip)

**Comment by quantum5** [comment]
Okay I made a new release, it should fix all these problems.

**Comment by quantum5** [comment]
If there are still problems, please feel free to reopen or create new issues as appropriate.
